version: "3.9"

services:
    app:
        container_name: munki_web
        image: munki_web
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"

